// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseLocalFile() {
  return window['go']['main']['App']['BrowseLocalFile']();
}

export function BrowseRoot() {
  return window['go']['main']['App']['BrowseRoot']();
}

export function ChooseSaveFile(arg1) {
  return window['go']['main']['App']['ChooseSaveFile'](arg1);
}

export function ClearCompleted() {
  return window['go']['main']['App']['ClearCompleted']();
}

export function GetInitialState() {
  return window['go']['main']['App']['GetInitialState']();
}

export function StartClientTransfer(arg1) {
  return window['go']['main']['App']['StartClientTransfer'](arg1);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
