// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BrowseLocalFile():Promise<string>;

export function BrowseRoot():Promise<string>;

export function ChooseSaveFile(arg1:string):Promise<string>;

export function ClearCompleted():Promise<void>;

export function GetInitialState():Promise<main.AppState>;

export function StartClientTransfer(arg1:main.ClientTransferRequest):Promise<void>;

export function StartServer(arg1:string):Promise<void>;

export function StopServer():Promise<void>;
